name: Test Action

inputs:
  environmentName:
    required: true
    type: string
  message:
    required: true
    type: string

runs:
  using: 'composite'
  steps:
    - name: Open The Door
      shell: bash
      working-directory: ./
      run: |
        echo "Open the door. environment name: ${{ inputs.environmentName }}"
        echo "${{ inputs.message }}"