name: Tag and Release Jobs For Merge

on:
  pull_request:
    branches:
      - 'release/**'
      - stage
      - main
    types:
      - closed
    paths:
      - '.github/**'
      - 'work/**'

jobs:
  goodbye:
    name: Goodbye
    if: ${{ github.event.pull_request.merged == true }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Close The Door
        shell: bash
        working-directory: ./
        run: |
          echo "Close the door!"