name: Deploy Monitoring sasaki

on:
  workflow_call:
    inputs:
      env_name:
        required: true
        type: string

env:
  MESSAGE: hijklmn

jobs:
  open_the_door:
    name: Open The Door
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.env_name }}
    env:
      environmentName: ${{ vars.ENVIRONMENT_NAME }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Echo Hello World
        shell: bash
        working-directory: ./
        run: |
          echo "SASAKI TEST. environment name: ${{ inputs.environmentName }}"
          echo "${{ inputs.message }}"
